default:
  stage: test
  region: us-west-1
  name: ${self:service}-${self:provider.stage}
  deploymentBucketName: btc-trading-${self:custom.default.stage}-storage
  projectName: ""
  coinrmarketcap_base_url: "sandbox.coinmarketcap.com"
  coingecko_base_url: "https://pro-api.coingecko.com/api/v3"
  polygon_io_base_url: "https://api.polygon.io"
  poylogon_io_authorization_key: ${{ secrets.POLYGON_IO_TEST_AUTH_KEY }}
  coinmarket_cap_api_key: ${{ secrets.COINMARKETCAP_API_KEY }}
plugins:
  - serverless-python-requirements
  - serverless-s3-deploy
lambda:
  concurrency: 1
  maxVersions: 1
  memorySize: 3008
  timeout: 900

sqs:
  sqsEndpoint: htts://sqs.$(self:provider.region).amazonaws.com
  messageRetentionPeriod: 86400 # 1 day -> (min: 1m, max: 14days, default: 4days)
  visibilityTimeout: 900 # (min: 30sec , max: 12hours, default: 30sec)
  maximumMessageSize: 262144 # 256KiB
  receiveMessageWaitTimeSeconds: 3 # (min:1 , max: 20,)


logRetentionInDays: 8

